POST /f84f2f23-b53a-49b2-87ad-023a31d568ca HTTP/1.1
Host: webhook.site
Content-Type: application/json
Content-Length: 85
 
{
    "productId": 2,
    "amount": 3,
    "deliveryAddress": "Any address test 2"
}